esphome:
  name: esp8266-auxiliar
  friendly_name: Esp8266 Auxiliar

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API

ota:
  password: "30704ba4d13d3ed109be72b4fccc4396"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Auxiliar"
    password: "TcNw6Qdph4eX"

captive_portal:

api:
  encryption:
    key: "A4t4+hIR+vApkrUoPLz29tq83HtBRUdSx7fhOpTZ8eg="
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return level / 100.0;'

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO2
    frequency: 50 Hz

servo:
  - id: my_servo
    output: pwm_output
